library(xlsx)
write.xlsx(mysa_crisis[["final"]][["series"]], 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/crisis_estacionalidad.xlsx', row.names = TRUE)
write.xlsx(mysa_comprar[["final"]][["series"]], 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/comprar_estacionalidad.xlsx')
write.xlsx(mysa_desempleo[["final"]][["series"]], 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/desempleo_estacionalidad.xlsx')
write.xlsx(mysa_infojobs[["final"]][["series"]], 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/infojobs_estacionalidad.xlsx')
write.xlsx(mysa_quiebra[["final"]][["series"]], 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/quiebra_estacionalidad.xlsx')


write.xlsx(serie_esi, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/ESI_FINAL.xlsx')
write.xlsx(ESIVLC, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/VLC.xlsx')
write.xlsx(ESIMAD, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/MAD.xlsx')
write.xlsx(ESIAN, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/AN.xlsx')
write.xlsx(ESIAR, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/AR.xlsx')
write.xlsx(ESIAS, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/AS.xlsx')
write.xlsx(ESICB, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/CB.xlsx')
write.xlsx(ESICL, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/CL.xlsx')
write.xlsx(ESICM, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/CM.xlsx')
write.xlsx(ESICN, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/CN.xlsx')
write.xlsx(ESICT, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/CT.xlsx')
write.xlsx(ESIEX, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/EX.xlsx')
write.xlsx(ESIGA, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/GA.xlsx')
write.xlsx(ESIIB, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/IB.xlsx')
write.xlsx(ESIMC, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/MC.xlsx')
write.xlsx(ESINC, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/NC.xlsx')
write.xlsx(ESIPV, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/PV.xlsx')
write.xlsx(ESIRI, 'C:/Users/inigo/OneDrive/Escritorio/4ºCD/TFG/TFG/RI.xlsx')